FROM mhart/alpine-node:8
MAINTAINER kaiyadavenport@gmail.com
WORKDIR /app
RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
  && pip install virtualenv \
  && rm -rf /var/cache/apk/*
COPY ./bot/package.json /app/package.json
COPY ./bot/yarn.lock /app/yarn.lock
RUN yarn install
COPY ./bot /app
ENTRYPOINT ["node", "main.js"]